# -*- coding: utf-8 -*-
"""BDOSN_LLM_CHATGPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VD2DXuRVgp8VtwFCnTzgf7_UGpS1T7zS
"""

!pip install openai panda tiktoken

"""This is the API projects and code for the OpenAI: https://platform.openai.com/examples"""

import numpy as np
import openai
import pandas as pd

import os
import openai
openai.organization = "org-fGGMS3DkPHdM86NBxk7x9XLC"
openai.api_key = os.getenv("API HERE")
openai.api_key = "API HERE"
openai.Model.list()

# giving mood to color: 
import os
import openai

openai.api_key = os.getenv("API HERE")
openai.api_key = "API HERE"
response = openai.Completion.create(
  model="text-davinci-003",
  prompt="The CSS code for a color like a black sky at dusk:\n\nbackground-color: #",
  temperature=0,
  max_tokens=64,
  top_p=1.0,
  frequency_penalty=0.0,
  presence_penalty=0.0,
  stop=[";"]
)

print(response)

# chat bot:
import os
import openai

openai.api_key = os.getenv("API HERE")
openai.api_key = "API HERE"
response = openai.Completion.create(
  model="text-davinci-003",
  prompt="The following is a conversation with an AI assistant. The assistant is helpful, creative, clever, and very friendly.\n\nHuman: Hello, who are you?\nAI: I am an AI created by OpenAI. How can I help you today?\nHuman: I'd like to cancel my subscription.\nAI:",
  # Change the temperature to give more exictement in the response 
  temperature=1.5,
  max_tokens=150,
  top_p=1,
  frequency_penalty=0.0,
  presence_penalty=0.6,
  stop=[" Human:", " AI:"]
)

print(response)

# Extrat keywords from text:
import os
import openai

openai.api_key = os.getenv("API HERE")
openai.api_key = "API HERE"

response = openai.Completion.create(
  model="text-davinci-003",
  prompt="Extract keywords from this text:\n\nBlack-on-black ware is a 20th- and 21st-century pottery tradition developed by the Puebloan Native American ceramic artists in Northern New Mexico. Traditional reduction-fired blackware has been made for centuries by pueblo artists. Black-on-black ware of the past century is produced with a smooth surface, with the designs applied through selective burnishing or the application of refractory slip. Another style involves carving or incising designs and selectively polishing the raised areas. For generations several families from Kha'po Owingeh and P'ohwhóge Owingeh pueblos have been making black-on-black ware with the techniques passed down from matriarch potters. Artists from other pueblos have also produced black-on-black ware. Several contemporary artists have created works honoring the pottery of their ancestors.",
  temperature=0.5,
  max_tokens=60,
  top_p=1.0,
  frequency_penalty=0.8,
  presence_penalty=0.0
)

# print(response)
print(response['choices'])

x = response['choices']
print(type(x))
print(x[0])

y = x[0]
print("This is y : ")
print(y)

print("This is the response text: ")
print(y['text'])

